language: cpp
install:
    # update, clean
  - sudo apt-get update
  - sudo apt-get autoclean
  - sudo apt-get clean
    # compilers
  - sudo apt-get install g++ cmake gfortran
    # math libraries
 # - sudo apt-get install libatlas-base-dev libatlas-dev
    # MPI
  - sudo apt-get install openmpi-bin libopenmpi-dev
    # PEP8 and py.test
  - sudo pip install pytest pep8
script:
  - python ./setup --mpi --fc=gfortran 
  - cd build
  - make VERBOSE=1 
    # show dependencies
  - ldd bin/example02
    #  run test (should end with 0)
  - cd bin
  - ls -lt
  #- exec "mpirun -np 2 ./example"
  - exec "mpirun -np 2 ./example02"


# turn off email notifications
notifications:
  email: false
